modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CerbonXD/QueenBeeMod/issues"

[[mods]]
    modId="queen_bee"
    version="${file.jarVersion}"
    displayName="Queen Bee"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/queen-bee"
    logoFile="logo.png"
    credits="Thanks for all people who helped me improve my mod"
    authors="CerbonXD"
    description='''
    Adds Queen Bee to Minecraft, with new items and a new Structure
    '''

[[dependencies.queen_bee]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.queen_bee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.queen_bee]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.queen_bee]]
    modId="cerbons_api"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
